# Generated by Django 5.0.10 on 2025-01-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericApp', '0002_file_name_alter_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('genres', models.TextField()),
            ],
        ),
    ]
