# Generated by Django 5.0.10 on 2025-01-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericApp', '0003_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
