# Generated by Django 5.0.10 on 2025-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericApp', '0004_alter_film_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
