# Generated by Django 5.0.10 on 2025-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericApp', '0005_alter_film_description_alter_film_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
